// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQDj6XEN0fNdZYTEr6CY8KVAD9sdp7IZw',
    appId: '1:318384006621:web:7c2e340767623f55fb4234',
    messagingSenderId: '318384006621',
    projectId: 'books-bazar-app',
    authDomain: 'books-bazar-app.firebaseapp.com',
    storageBucket: 'books-bazar-app.firebasestorage.app',
    measurementId: 'G-G51TDB2LXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbzrRQW4WpHcpAgMxqfX80ayeSXNP-wCo',
    appId: '1:318384006621:android:69d6598365f5b70ffb4234',
    messagingSenderId: '318384006621',
    projectId: 'books-bazar-app',
    storageBucket: 'books-bazar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN_vpXkreSGKBEue2LJerq9yud9ujshQI',
    appId: '1:318384006621:ios:66a9fd8eb9248383fb4234',
    messagingSenderId: '318384006621',
    projectId: 'books-bazar-app',
    storageBucket: 'books-bazar-app.firebasestorage.app',
    iosBundleId: 'com.example.booksBazarApp',
  );
}
